CREATE DATABASE LEARNING
USE LEARNING
CREATE TABLE ACCOUNT(
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NAME_STUDENT VARCHAR(255),
CLASS VARCHAR(255),
SCHOOL VARCHAR(255)
)
select * from dbo.ACCOUNT